spring.datasource.url=jdbc:sqlite:../../DB/ExpenseCalculating_db
srping.datasource.driver-class-name=org.sqlite.JDBC

srping.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
